ESX Version
Xilophinum/posters pull request #1
Opened 2024-04-22 11:10 UTC by FripeX

Added ESX Version

2024-04-22 13:17 UTC, Mathu-lmn requested changes
Please don't overwrite the existing script / code, but make it a configuration instead !

2024-04-22 13:17 UTC, Mathu-lmn commented on lua/client.lua
> +local ESX = nil
I'd suggest adding a configuration option instead of deleting this QB support

2024-04-22 13:17 UTC, Mathu-lmn commented on lua/client.lua
> +AddEventHandler('esx:onPlayerLogout', function()
This is an unneeded change....

2024-04-22 13:17 UTC, Mathu-lmn commented on lua/client.lua
> +                        TriggerServerEvent("posters:deleteImage", currentKey, PlayerData.identifier == currentPoster.cid)
Same goes here, use the config option !

2024-04-22 17:30 UTC, FripeX commented on lua/client.lua
> +local ESX = nil
added

2024-04-22 21:44 UTC, Mathu-lmn commented
Readme got updated, might be worth checking if it fits your needs

2024-04-22 21:45 UTC, Mathu-lmn commented
Also might want to set default framework to qb

2024-04-23 14:04 UTC, FripeX commented
> Anyone validate this works before I merge?

All good, you can just check the config if you want to set the default framework to qb

2024-04-30 22:13 UTC, closed without merging